package de.mathiiis.notes.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * A single note page
 *
 * > id is autogenerated row id
 * > content is full plain text body, title is derived from first line
 * > createdAt and updatedAt are unix millis used for ordering and display
 */
@Entity(tableName = "notes")
data class Note(
    @PrimaryKey(autoGenerate = true) val id: Long = 0L,
    val content: String = "",
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis(),
)
